# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f2fcf2e99740e53527a2d2ea703525686b7a40e2cdd4b576a4715ffe6f46fdb86feb357fe13f928c35ffb52768628813449ad662ad7615fb046164907ef438

test:
  secret_key_base: c34eefc47c64b51e9828333665386226ae206b44af400a2d87437e4a0e5d2e08a8b399470166a6e8be7433a9f371b3b28143f98f3b9b5bb61b86fb4af9f8e55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
